backend:
  name: github
  repo: PhantomProductions501/ArtOfPhantom
  branch: main
  base_url: https://phantomproductions501.github.io
  auth_endpoint: /ArtOfPhantom/auth

media_folder: "img/uploads"        # Carpeta donde se guardan las imágenes
public_folder: "/img/uploads"      # Ruta pública
publish_mode: editorial_workflow

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "img/uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }
